[application]
name = "fnk"

default_platform = "web"

out_dir = "dist"

asset_dir = "public"

[web.app]

title = "FnK"

[web.watcher]

index_on_404 = true

[web.resource]

[web.resource.dev]

[[web.proxy]]
backend = "http://[::1]:8080/v1/"
