[application]
name = "fnk"

default_platform = "web"

out_dir = "dist"

asset_dir = "public"

[web.app]

title = "FnK"

[web.watcher]

index_on_404 = true

[web.resource]

[web.resource.dev]

[[web.proxy]]
backend = "http://[::1]:8081/v1/"
# backend = "https://[::1]:8081/v1/"

# [web.https]
# enabled = true
# mkcert = true
# cert_path = "../ssl/cert.pem"
# key_path = "../ssl/key.pem"
